import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">Inicio</Link>
        </li>
        <li>
          <Link to="/logintwo">LoginTwo</Link>
        </li>
        <li>
          <Link to="/loginone">LoginOne</Link>
        </li>
        <li>
          <Link to="/login">Login</Link>
        </li>
        <li>
          <Link to="/registrotwo">RegistroTwo</Link>
        </li>
        <li>
          <Link to="/registro">Registro</Link>
        </li>
        <li>
          <Link to="/registroone">RegistroOne</Link>
        </li>
        <li>
          <Link to="/homeone">HomeOne</Link>
        </li>
        <li>
          <Link to="/hometwo">HomeTwo</Link>
        </li>
        <li>
          <Link to="/formulario">Formulario</Link>
        </li>
        <li>
          <Link to="/busqueda">Busqueda</Link>
        </li>
        <li>
          <Link to="/homethree">HomeThree</Link>
        </li>
        <li>
          <Link to="/homefour">HomeFour</Link>
        </li>
        <li>
          <Link to="/homefive">HomeFive</Link>
        </li>
        <li>
          <Link to="/homesix">HomeSix</Link>
        </li>
        <li>
          <Link to="/generos">Generos</Link>
        </li>
        <li>
          <Link to="/homenine">HomeNine</Link>
        </li>
        <li>
          <Link to="/homeseven">HomeSeven</Link>
        </li>
        <li>
          <Link to="/homeeight">HomeEight</Link>
        </li>
        <li>
          <Link to="/hometen">HomeTen</Link>
        </li>
        <li>
          <Link to="/homeeleven">HomeEleven</Link>
        </li>
        <li>
          <Link to="/hometwelve">HomeTwelve</Link>
        </li>
        <li>
          <Link to="/descripciondepelicula">DescripciondePelicula</Link>
        </li>
        <li>
          <Link to="/busquedathree">BusquedaThree</Link>
        </li>
        <li>
          <Link to="/busquedaone">BusquedaOne</Link>
        </li>
        <li>
          <Link to="/busquedatwo">BusquedaTwo</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
